from __future__ import annotations

import math
import queue as _queue
import time
import tkinter as tk
from typing import Callable

# ── palette ──────────────────────────────────────────────────────────────────
# Terminal Instrument design system (generated by Stitch, Memory Compiler project).
# "Functional Brutalism" — near-black surfaces, Electric Cyan accent, salmon stop.
PILL_BG      = "#131314"     # surface
WAVE_BG      = "#0e0e0f"     # surface_container_lowest
WAVE_BORDER  = "#2a2a2b"     # surface_container_high (subtle edge)
TEXT         = "#e5e2e3"     # on_surface
TEXT_DIM     = "#849495"     # outline
ACCENT_REC   = "#00F5FF"     # Electric Cyan — primary_container
ACCENT_PROC  = "#ffdb3f"     # tertiary_container (amber — processing)
ACCENT_DONE  = "#63f7ff"     # primary_fixed — bright cyan
ACCENT_WARN  = "#ffdb3f"
BTN_CANCEL   = "#131314"     # invisible background (glyph-only)
BTN_STOP_BG  = "#ffb4ab"     # error — soft salmon (not harsh red)
BTN_STOP_FG  = "#690005"     # on_error — deep crimson label on salmon
MODE_ON_BG   = "#00F5FF"     # Electric Cyan — active chip
MODE_ON_FG   = "#003739"     # on_primary — dark teal on cyan
MODE_OFF_BG  = "#131314"     # flat on pill surface
MODE_OFF_FG  = "#849495"     # outline — dim label

# ── waveform config ──────────────────────────────────────────────────────────
NUM_BARS    = 28
BAR_W       = 4
BAR_GAP     = 2
WAVE_W      = NUM_BARS * (BAR_W + BAR_GAP) - BAR_GAP   # 166 px
WAVE_H      = 42
DECAY       = 0.80
AMP_SCALE   = 12.0           # RMS → 0..1 (typical speech RMS ≈ 0.03–0.08)

# ── layout ───────────────────────────────────────────────────────────────────
PAD_X           = 22
PAD_Y           = 14
BOTTOM_OFFSET   = 150        # px above bottom of screen (was 80 — too close to taskbar)
TICK_MS         = 50
SPIN_MS         = 110

MODE_OPTIONS = ["raw", "clean", "context"]
MODE_HELP = {
    "raw":     "Transcript only — no AI, no rephrasing. Fastest.",
    "clean":   "Fix grammar & remove filler words (um, uh). One quick AI call.",
    "context": "Full prompt with project KB context. Best for Claude Code.",
}
SPIN_FRAMES = ["◐", "◓", "◑", "◒"]


def _level_to_color(v: float) -> str:
    """Map amplitude 0..1 to the Terminal Instrument waveform gradient.

    Cyan spectrum with a salmon peak-indicator when bars clip — classic
    audio-studio VU styling translated to the Stitch palette.
    """
    if v > 0.85: return "#ffb4ab"   # peak / clip — error salmon
    if v > 0.65: return "#63f7ff"   # primary_fixed — brightest cyan
    if v > 0.40: return "#00F5FF"   # Electric Cyan
    if v > 0.20: return "#00dce5"   # primary_fixed_dim
    if v > 0.05: return "#044f52"   # secondary_container — deep teal
    return "#0e0e0f"                 # surface_container_lowest (invisible floor)


class Pill:
    """Floating recording pill shown in the bottom-centre of the screen.

    Layout (left → right):
        [mic] [live waveform] [elapsed] [mode chips] [✕] [■ Stop]
    """

    def __init__(
        self,
        root: tk.Tk,
        on_cancel: Callable[[], None],
        on_stop: Callable[[], None],
        on_mode_change: Callable[[str], None],
        initial_mode: str = "context",
        mode_lock: bool = False,
        level_queue: _queue.Queue[float] | None = None,
        on_quit: Callable[[], None] | None = None,
    ) -> None:
        self._root = root
        self._on_cancel = on_cancel
        self._on_stop = on_stop
        self._on_mode_change = on_mode_change
        self._on_quit = on_quit
        self._mode_lock = mode_lock
        self._lq = level_queue
        self._current_mode = initial_mode

        self._bar_levels: list[float] = [0.0] * NUM_BARS
        self._bar_ids: list[int] = []
        self._animate_job: str | None = None
        self._spin_idx = 0
        self._is_recording = False
        self._start_time = 0.0

        # ── window ─────────────────────────────────────────────────────────
        self._win = tk.Toplevel(root)
        self._win.overrideredirect(True)
        self._win.wm_attributes("-topmost", True)
        self._win.wm_attributes("-alpha", 0.96)
        self._win.configure(bg=PILL_BG)
        self._win.withdraw()

        self._frame = tk.Frame(self._win, bg=PILL_BG, padx=PAD_X, pady=PAD_Y)
        self._frame.pack()

        col = 0

        # — live-indicator glyph (cyan pulsing ● rather than a mic emoji) —
        self._icon_lbl = tk.Label(
            self._frame, text="●", fg=ACCENT_REC, bg=PILL_BG,
            font=("Segoe UI", 20),
        )
        self._icon_lbl.grid(row=0, column=col, padx=(0, 16))
        col += 1

        # — waveform canvas —
        self._wave_cv = tk.Canvas(
            self._frame, width=WAVE_W, height=WAVE_H,
            bg=WAVE_BG, highlightthickness=1,
            highlightbackground=WAVE_BORDER,
        )
        self._wave_cv.grid(row=0, column=col, padx=(0, 14))
        col += 1

        # Centre reference line so the waveform reads even with no audio
        self._wave_cv.create_line(
            0, WAVE_H // 2, WAVE_W, WAVE_H // 2,
            fill="#1c1b1c", width=1,
        )
        # Pre-allocate bar rectangles — we reposition rather than delete/recreate
        # to avoid canvas flicker and keep the 50 ms tick cheap.
        yc = WAVE_H // 2
        for i in range(NUM_BARS):
            x0 = i * (BAR_W + BAR_GAP)
            bid = self._wave_cv.create_rectangle(
                x0, yc - 1, x0 + BAR_W, yc + 1,
                fill=_level_to_color(0.0), outline="",
            )
            self._bar_ids.append(bid)

        # — elapsed timer —
        self._elapsed_lbl = tk.Label(
            self._frame, text="0.0s", fg=TEXT_DIM, bg=PILL_BG,
            font=("Consolas", 12), width=5, anchor="e",
        )
        self._elapsed_lbl.grid(row=0, column=col, padx=(0, 16))
        col += 1

        # — mode chips (hidden when locked) —
        self._mode_btns: dict[str, tk.Label] = {}
        if not mode_lock:
            self._mf = tk.Frame(self._frame, bg=PILL_BG)
            self._mf.grid(row=0, column=col, padx=(0, 16))
            col += 1
            for m in MODE_OPTIONS:
                active = m == self._current_mode
                lbl = tk.Label(
                    self._mf, text=m.upper(),
                    fg=MODE_ON_FG if active else MODE_OFF_FG,
                    bg=MODE_ON_BG if active else MODE_OFF_BG,
                    font=("Segoe UI", 9, "bold"),
                    padx=10, pady=5, cursor="hand2",
                )
                lbl.pack(side=tk.LEFT, padx=2)
                lbl.bind("<Button-1>", lambda _e, mode=m: self._select_mode(mode))
                lbl.bind("<Enter>", lambda _e, w=lbl, mm=m: self._on_mode_hover(w, mm, True))
                lbl.bind("<Leave>", lambda _e, w=lbl, mm=m: self._on_mode_hover(w, mm, False))
                self._mode_btns[m] = lbl

        # — cancel button (glyph-only, dim outline) —
        self._cancel_btn = tk.Button(
            self._frame, text="✕", bg=BTN_CANCEL, fg=TEXT_DIM,
            relief=tk.FLAT, font=("Segoe UI", 12), padx=9, pady=4,
            cursor="hand2", activebackground="#201f20",
            activeforeground=TEXT, command=self._on_cancel,
            borderwidth=0, highlightthickness=0,
        )
        self._cancel_btn.grid(row=0, column=col, padx=(0, 6))
        col += 1

        # — stop button (salmon primary action) —
        self._stop_btn = tk.Button(
            self._frame, text="■  STOP", bg=BTN_STOP_BG, fg=BTN_STOP_FG,
            relief=tk.FLAT, font=("Segoe UI", 11, "bold"), padx=14, pady=4,
            cursor="hand2", activebackground="#ffdad6",
            activeforeground="#490006", command=self._on_stop,
            borderwidth=0, highlightthickness=0,
        )
        self._stop_btn.grid(row=0, column=col)
        col += 1

        # — quit button (power glyph — kills the whole app; distinct from cancel) —
        # Kept in its own column with a wider left pad so it reads as a separate
        # concern from the recording controls. Stays visible in every state.
        self._quit_btn = tk.Button(
            self._frame, text="⏻", bg=PILL_BG, fg="#5a6478",
            relief=tk.FLAT, font=("Segoe UI", 13), padx=6, pady=2,
            cursor="hand2", activebackground="#2a1414",
            activeforeground="#ff8899", command=self._handle_quit,
            borderwidth=0, highlightthickness=0,
        )
        self._quit_btn.grid(row=0, column=col, padx=(14, 0))

        self._bind_drag()

    def _handle_quit(self) -> None:
        """Close the floating pill immediately, then hand off to the app quit
        handler so the tray icon, hotkey listener, and executor all shut down.
        The pill vanishes instantly — no waiting for the shutdown to complete."""
        self._stop_animate()
        self._win.withdraw()
        if self._on_quit is not None:
            # Defer to the next tick so this button's click handler returns first;
            # otherwise tk's event loop can deadlock during the shutdown cascade.
            self._root.after(50, self._on_quit)

    # ── mode chips ────────────────────────────────────────────────────────────

    def _select_mode(self, mode: str) -> None:
        if self._mode_lock:
            return
        self._current_mode = mode
        for m, btn in self._mode_btns.items():
            active = m == mode
            btn.configure(
                fg=MODE_ON_FG if active else MODE_OFF_FG,
                bg=MODE_ON_BG if active else MODE_OFF_BG,
            )
        self._on_mode_change(mode)

    def _on_mode_hover(self, widget: tk.Label, mode: str, entering: bool) -> None:
        if mode == self._current_mode:
            return
        widget.configure(bg="#1a1e30" if entering else MODE_OFF_BG,
                         fg="#8890ae" if entering else MODE_OFF_FG)

    # ── window placement & drag ───────────────────────────────────────────────

    def _center_bottom(self) -> None:
        self._win.update_idletasks()
        sw = self._root.winfo_screenwidth()
        sh = self._root.winfo_screenheight()
        w = self._win.winfo_reqwidth()
        h = self._win.winfo_reqheight()
        x = (sw - w) // 2
        y = sh - h - BOTTOM_OFFSET
        self._win.geometry(f"+{x}+{y}")

    def _bind_drag(self) -> None:
        self._drag_x = 0
        self._drag_y = 0

        def on_press(ev: tk.Event) -> None:
            self._drag_x = ev.x
            self._drag_y = ev.y

        def on_motion(ev: tk.Event) -> None:
            nx = self._win.winfo_x() + ev.x - self._drag_x
            ny = self._win.winfo_y() + ev.y - self._drag_y
            self._win.geometry(f"+{nx}+{ny}")

        # Drag from the icon, waveform, or elapsed area (not from interactive chips)
        for target in (self._frame, self._icon_lbl, self._wave_cv, self._elapsed_lbl):
            target.bind("<ButtonPress-1>", on_press)
            target.bind("<B1-Motion>", on_motion)

    # ── animation loops ───────────────────────────────────────────────────────

    def _stop_animate(self) -> None:
        if self._animate_job is not None:
            self._root.after_cancel(self._animate_job)
            self._animate_job = None

    def _redraw_bars(self) -> None:
        yc = WAVE_H // 2
        max_half = WAVE_H / 2 - 2
        for i, (bid, v) in enumerate(zip(self._bar_ids, self._bar_levels)):
            half_h = max(1, int(v * max_half))
            x0 = i * (BAR_W + BAR_GAP)
            self._wave_cv.coords(bid, x0, yc - half_h, x0 + BAR_W, yc + half_h)
            self._wave_cv.itemconfig(bid, fill=_level_to_color(v))

    def _tick_waveform(self) -> None:
        """50 ms tick — drain real mic levels, shift bars left, add newest on right."""
        level = 0.0
        if self._lq is not None:
            # Drain queue, keep the latest amplitude. If the mic produced several
            # frames since last tick we only render the most recent one.
            try:
                while True:
                    level = self._lq.get_nowait()
            except _queue.Empty:
                pass
            level = min(1.0, level * AMP_SCALE)
        else:
            # No real audio source — gentle breathing pulse so the panel still
            # looks alive. Kept visibly lower than real-speech levels.
            level = 0.14 + 0.05 * math.sin(time.time() * 3.8)

        # Shift bars left with a decay so older bars fade out smoothly.
        for i in range(NUM_BARS - 1):
            self._bar_levels[i] = self._bar_levels[i + 1] * DECAY
        self._bar_levels[-1] = level

        self._redraw_bars()

        elapsed = time.time() - self._start_time
        self._elapsed_lbl.configure(text=f"{elapsed:4.1f}s")

        self._animate_job = self._root.after(TICK_MS, self._tick_waveform)

    def _tick_spinner(self) -> None:
        self._spin_idx = (self._spin_idx + 1) % len(SPIN_FRAMES)
        self._icon_lbl.configure(
            text=SPIN_FRAMES[self._spin_idx],
            fg=ACCENT_PROC,
            font=("Segoe UI", 20),
        )
        self._animate_job = self._root.after(SPIN_MS, self._tick_spinner)

    def _reset_bars(self) -> None:
        self._bar_levels = [0.0] * NUM_BARS
        self._redraw_bars()

    # ── public state API (called from main loop / worker thread) ──────────────

    def show_recording(self) -> None:
        self._root.after(0, self._do_show_recording)

    def _do_show_recording(self) -> None:
        self._stop_animate()
        self._is_recording = True
        self._start_time = time.time()
        self._icon_lbl.configure(text="●", fg=ACCENT_REC, font=("Segoe UI", 20))
        self._elapsed_lbl.configure(text="0.0s", fg=TEXT_DIM)
        self._cancel_btn.grid()
        self._stop_btn.grid()
        self._win.deiconify()
        self._center_bottom()
        self._animate_job = self._root.after(TICK_MS, self._tick_waveform)

    def show_processing(self) -> None:
        self._root.after(0, self._do_show_processing)

    def _do_show_processing(self) -> None:
        self._stop_animate()
        self._is_recording = False
        self._elapsed_lbl.configure(text="…", fg=ACCENT_PROC)
        self._cancel_btn.grid_remove()
        self._stop_btn.grid_remove()
        self._tick_spinner()

    def show_done(self) -> None:
        self._root.after(0, self._do_show_done)

    def _do_show_done(self) -> None:
        self._stop_animate()
        self._is_recording = False
        self._icon_lbl.configure(text="✓", fg=ACCENT_DONE, font=("Segoe UI", 20, "bold"))
        self._elapsed_lbl.configure(text="done", fg=ACCENT_DONE)
        self._root.after(900, self._do_hide)

    def show_error(self, message: str, duration_ms: int = 1500) -> None:
        self._root.after(0, lambda: self._do_show_error(message, duration_ms))

    def _do_show_error(self, message: str, duration_ms: int) -> None:
        self._stop_animate()
        self._is_recording = False
        self._icon_lbl.configure(text="⚠", fg=ACCENT_WARN, font=("Segoe UI", 18))
        self._elapsed_lbl.configure(text=message[:10], fg=ACCENT_WARN)
        self._root.after(duration_ms, self._do_hide)

    def hide(self) -> None:
        self._root.after(0, self._do_hide)

    def _do_hide(self) -> None:
        self._stop_animate()
        self._is_recording = False
        self._icon_lbl.configure(text="●", fg=ACCENT_REC, font=("Segoe UI", 20))
        self._elapsed_lbl.configure(text="0.0s", fg=TEXT_DIM)
        self._reset_bars()
        self._win.withdraw()

    def set_mode(self, mode: str) -> None:
        if not self._mode_lock:
            self._root.after(0, lambda: self._select_mode(mode))
